name: Create-NewVersion-And-Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Call-Update-Version:
    uses: ./.github/workflows/UpdateVersion.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  Call-CreatePackage:
    needs: [Call-Update-Version]
    uses: ./.github/workflows/CreatePackage.yml
    with:
      ref: ${{ github.event.inputs.tag }}

  Call-Release:
    needs: [Call-CreatePackage]
    uses: ./.github/workflows/CreateRelease.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  SendVpmRS64Net:
    runs-on: ubuntu-latest
    needs: [Call-Release]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.VPM_REPO_TOKEN }}
          repository: ReinaS-64892/vpm.rs64.net
          event-type: add_new_version
          client-payload: '{"repository": "TTCE-Wgpu", "tag": "${{ inputs.tag }}"}'
