name: Create-NewVersion-And-Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Call-Update-Version:
    uses: ./.github/workflows/UpdateVersion.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  Call-CreatePackage:
    needs: [Call-Update-Version]
    uses: ./.github/workflows/CreatePackage.yml
    with:
      ref: ${{ github.event.inputs.tag }}

  Call-Release:
    needs: [Call-CreatePackage]
    uses: ./.github/workflows/CreateRelease.yml
    with:
      tag: ${{ github.event.inputs.tag }}

