name: CreateRelease

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
    - name: DownloadArtifact
      uses: actions/download-artifact@v4
      with:
        name: TTCE-Wgpu

    - name: rename
      run: |
        mv TTCE-Wgpu.zip ttce-wgpu-${{ inputs.tag }}.zip

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: ./Repo
        fetch-tags: true
        ref: ${{ inputs.tag }}

    - name: CrateRelease
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        files: |
          ttce-wgpu-${{ inputs.tag }}.zip
          Repo/TTCE-Wgpu/UnityPackageMetaData/package.json
