name: DotnetTest
on: push

jobs:
  dotnet-test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - name: RustCore Build to Genereate csbinding
        run: |
          cd ttce-wgpu-rust-core
          cargo build


      - name: Create ProjectPackages directory
        run: |
          mkdir ProjectPackages
      - uses: actions/checkout@v4
        with:
          repository: ReinaS-64892/TexTransTool
          ref: Improved-TexTransCore
          path: ProjectPackages/TexTransTool

      - name: Debug output
        run: |
          ls
          echo "---"
          cd ProjectPackages
          ls
          echo "---"
          cd TexTransTool
          ls


      - uses: actions/setup-dotnet@v4
      - name: Run test
        run: |
          cd TTCE-Wgpu.Tests
          dotnet test
