name: DotnetTest
on: push

jobs:
  dotnet-test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ProjectPackages directory
        run: |
          mkdir ProjectPackages
      - uses: actions/checkout@v4
        with:
          repository: ReinaS-64892/TexTransTool
          ref: Improved-TexTransCore
          path: ProjectPackages

      - name: Debug output
        run: |
          ls
          cd ProjectPackages
          ls


      - uses: actions/setup-dotnet@v4
      - name: Run test
        run: |
          cd TTCE-Wgpu.Tests
          dotnet test
