name: DirectXShaderCompiler Build
on: [workflow_call, workflow_dispatch]

jobs:
    dxc-build:
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
          with:
            repository: microsoft/DirectXShaderCompiler

