name: DirectXShaderCompiler Build
on: [workflow_call, workflow_dispatch, push]

jobs:
  dxc-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/DirectXShaderCompiler
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: build set up (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install ninja-build

          curl https://apt.llvm.org/llvm.sh > ./llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 18

          sudo apt-get install libc++-18-dev

      - name: build set up (mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install ninja

      - name: cache
        uses: actions/cache@v4
        with:
          path: dxc_build
          key: ${{matrix.os}}_dxc_build

      - name: run build (ubuntu or mac)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          cmake ./ -B dxc_build -C ./cmake/caches/PredefinedParams.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
          ninja -C dxc_build

          echo "--- build end ---"

          cd dxc_build/lib
          ls

      - name: setup to build (windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -Force dxc_build
          $wp=(gl).Path
          utils\hct\hctstart.cmd .\ $wp\dxc_build
          utils\hct\hctbuild.cmd -release -spirv -buildoutdir $wp\dxc_build

          echo "--- build end ---"

          cd dxc_build
          ls .\Release\bin
