name: RustCoreBuild

on: push

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cd ttce-wgpu-rust-core
        cargo build --verbose
