name: RustCoreBuild

on: push

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ttce-wgpu-rust-core -> target

      - name: Debug-ToolVersion
        run: |
          cargo -V
          rustc -V

      - name: Build
        run: |
          cd ttce-wgpu-rust-core
          cargo build --release --verbose

      - name: out-put upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-core-${{ matrix.os }}
          path: |
            ttce-wgpu-rust-core/target/*
              
      - name: Debug-Output
        run: |
          ls ttce-wgpu-rust-core/target/release
