name: RustCoreBuild

on: push

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Move RustCore Directory
      run: cd ttce-wgpu-rust-core
    - name: Build
      run: cargo build --verbose
