name: UpdateVersion

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
      - name: run update version
        run: |
          cd .github/workflows/DotnetWorkflowScript/WriteVersion
          dotnet run ${{ github.event.inputs.tag }}

      - name: git commit and push tag
        run: |
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add TTCE-Wgpu/UnityPackageMetaData/package.json
          git commit -m "chore: update TTCE-Wgpu ${{ github.event.inputs.tag }}!"
          git tag ${{ github.event.inputs.tag }}
          git push
          git push origin ${{ github.event.inputs.tag }}
